apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-ci-cd-java-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: devops.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devops-ci-cd-java-service
                port:
                  number: 8080
