apiVersion: v1
kind: Service
metadata:
  name: devops-ci-cd-java-service
spec:
  selector:
    app: devops-ci-cd-java
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
